---
abstract: 'Scrypt password based key derivation function'
author:
  - 'Karel Miko'
build_requires:
  ExtUtils::CBuilder: 0
  MIME::Base64: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-ScryptKDF
provides:
  Crypt::ScryptKDF:
    file: lib/Crypt/ScryptKDF.pm
    version: 0.004
requires:
  MIME::Base64: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
